apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  namespace: spark
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
      nodePort: 30077
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30080
